# Internal functions for DOT and Mermaid output.
# None of these are exported; users interact only via graph_to_outputs().


# ── DOT builder ───────────────────────────────────────────────────────────────

#' @keywords internal
#' @noRd
.dot_build <- function(adj, np, directed,
                       adj_ov = NULL, ovcol = "#999999",
                       ovw = 1.0, ovstyle = "dashed",
                       edge_labels = NULL,
                       overlay_edge_labels = NULL,
                       edge_props = NULL,
                       overlay_edge_props = NULL) {
  n   <- nrow(adj)
  gkw <- if (directed) "digraph" else "graph"
  eop <- if (directed) "->"     else "--"

  # Wrap a string in double-quotes, escaping any internal double-quotes
  .dq <- function(s) paste0('"', gsub('"', '\\"', s, fixed = TRUE), '"')

  .dot_lt <- function(lt) {
    switch(tolower(trimws(as.character(lt))),
      dashed = "dashed", dotted = "dotted", longdash = "dashed", twodash = "dashed",
      "solid"
    )
  }

  dot_shape <- function(s) {
    switch(tolower(trimws(s)),
      circle  = "circle",
      ellipse = "ellipse",
      diamond = "diamond",
      rounded = "box",    # style="filled,rounded" applied separately
      "box"               # default
    )
  }
  dot_style <- function(s) {
    if (tolower(trimws(s)) == "rounded") "filled,rounded" else "filled"
  }

  out <- c(
    "// Generated by graphout::graph_to_outputs()",
    "// Render with fixed positions : neato -n -Tsvg graph.dot -o graph.svg",
    "// Render with auto layout     : dot   -Tsvg graph.dot -o graph.svg",
    sprintf("%s G {", gkw),
    '  graph [fontname="Helvetica" splines=true overlap=false]',
    '  node  [fontname="Helvetica" fixedsize=false]',
    '  edge  [fontname="Helvetica"]',
    ""
  )

  for (i in seq_len(n)) {
    lbl  <- gsub('"',  '\\"',  as.character(np$label[i]), fixed = TRUE)
    lbl  <- gsub("\n", "\\n",  lbl, fixed = TRUE)
    # Graphviz uses inches; convert px assuming 96 dpi
    w_in <- round(np$width[i]  / 96, 3)
    h_in <- round(np$height[i] / 96, 3)
    # Graphviz y-axis points upward; SVG y-axis points downward → negate y
    pos_str <- paste0(np$x[i], ",", -np$y[i], "!")

    attrs <- paste(
      paste0("label=",     .dq(lbl)),
      paste0("shape=",     dot_shape(np$shape[i])),
      paste0("style=",     .dq(dot_style(np$shape[i]))),
      paste0("fillcolor=", .dq(np$colour[i])),
      paste0("fontcolor=", .dq(np$fontcolour[i])),
      paste0("color=",     .dq(np$stroke[i])),
      paste0("fontsize=",  np$fontsize[i]),
      paste0("width=",     w_in),
      paste0("height=",    h_in),
      paste0("pos=",       .dq(pos_str))
    )
    out <- c(out, paste0("  ", .dq(np$id[i]), " [", attrs, "]"))
  }

  out <- c(out, "")

  done <- matrix(FALSE, n, n)
  for (i in seq_len(n)) {
    for (j in seq_len(n)) {
      v <- adj[i, j]
      if (v == 0 || (!directed && done[j, i])) next
      lbl_txt <- NULL
      if (!is.null(edge_labels) && !is.na(edge_labels[i, j]) &&
          nzchar(trimws(as.character(edge_labels[i, j]))))
        lbl_txt <- trimws(as.character(edge_labels[i, j]))
      else if (v != 1)
        lbl_txt <- format(v, trim = TRUE)
      # Per-edge visual style from edge_props
      ep_col <- if (!is.null(edge_props)) {
        idx <- which(edge_props$weight == v)
        if (length(idx) > 0L && "colour" %in% names(edge_props) && !is.na(edge_props$colour[idx[1L]]))
          edge_props$colour[idx[1L]] else NULL
      } else NULL
      ep_w  <- if (!is.null(edge_props)) {
        idx <- which(edge_props$weight == v)
        if (length(idx) > 0L && "width" %in% names(edge_props) && !is.na(edge_props$width[idx[1L]]))
          edge_props$width[idx[1L]] else NULL
      } else NULL
      ep_lt <- if (!is.null(edge_props)) {
        idx <- which(edge_props$weight == v)
        if (length(idx) > 0L && "linetype" %in% names(edge_props) && !is.na(edge_props$linetype[idx[1L]]))
          edge_props$linetype[idx[1L]] else NULL
      } else NULL
      ep_attrs <- c(
        if (!is.null(lbl_txt))  paste0("label=",    .dq(lbl_txt)),
        if (!is.null(ep_col))   paste0("color=",    .dq(ep_col)),
        if (!is.null(ep_w))     paste0("penwidth=",  ep_w),
        if (!is.null(ep_lt))    paste0("style=",    .dq(.dot_lt(ep_lt)))
      )
      elbl <- if (length(ep_attrs) > 0L) paste0(" [", paste(ep_attrs, collapse = ", "), "]") else ""
      out     <- c(out, paste0("  ", .dq(np$id[i]), " ", eop, " ",
                               .dq(np$id[j]), elbl))
      done[i, j] <- TRUE
    }
  }

  if (!is.null(adj_ov)) {
    n_ov   <- nrow(adj_ov)
    out  <- c(out, "", "  // overlay edges")
    done_ov <- matrix(FALSE, n_ov, n_ov)
    for (i in seq_len(n_ov)) {
      for (j in seq_len(n_ov)) {
        v <- adj_ov[i, j]
        if (v == 0 || (!directed && done_ov[j, i])) next
        ov_lbl_txt <- NULL
        if (!is.null(overlay_edge_labels) && !is.na(overlay_edge_labels[i, j]) &&
            nzchar(trimws(as.character(overlay_edge_labels[i, j]))))
          ov_lbl_txt <- trimws(as.character(overlay_edge_labels[i, j]))
        else if (v != 1)
          ov_lbl_txt <- format(v, trim = TRUE)
        # Per-overlay-edge visual style from overlay_edge_props
        ovep_col <- if (!is.null(overlay_edge_props)) {
          idx <- which(overlay_edge_props$weight == v)
          if (length(idx) > 0L && "colour" %in% names(overlay_edge_props) && !is.na(overlay_edge_props$colour[idx[1L]]))
            overlay_edge_props$colour[idx[1L]] else ovcol
        } else ovcol
        ovep_w  <- if (!is.null(overlay_edge_props)) {
          idx <- which(overlay_edge_props$weight == v)
          if (length(idx) > 0L && "width" %in% names(overlay_edge_props) && !is.na(overlay_edge_props$width[idx[1L]]))
            overlay_edge_props$width[idx[1L]] else ovw
        } else ovw
        ovep_lt <- if (!is.null(overlay_edge_props)) {
          idx <- which(overlay_edge_props$weight == v)
          if (length(idx) > 0L && "linetype" %in% names(overlay_edge_props) && !is.na(overlay_edge_props$linetype[idx[1L]]))
            .dot_lt(overlay_edge_props$linetype[idx[1L]]) else ovstyle
        } else ovstyle
        ov_dot_style <- paste0('style=', .dq(ovep_lt),
                               ', color=', .dq(ovep_col),
                               ', penwidth=', ovep_w)
        elbl <- if (!is.null(ov_lbl_txt)) paste0(" label=", .dq(ov_lbl_txt), ",") else " "
        out  <- c(out, paste0("  ", .dq(np$id[i]), " ", eop, " ",
                              .dq(np$id[j]), " [", elbl, ov_dot_style, "]"))
        done_ov[i, j] <- TRUE
      }
    }
  }

  out <- c(out, "}")
  paste(out, collapse = "\n")
}


# ── Mermaid builder ───────────────────────────────────────────────────────────

#' @keywords internal
#' @noRd
.mmd_build <- function(adj, np, directed,
                       adj_ov = NULL, ovstyle = "dashed",
                       edge_labels = NULL,
                       overlay_edge_labels = NULL,
                       edge_props = NULL,
                       overlay_edge_props = NULL) {
  n <- nrow(adj)

  # Sanitise to a valid Mermaid node identifier: [A-Za-z0-9_], no leading digit
  .mid <- function(s) {
    s <- gsub("[^A-Za-z0-9_]", "_", s)
    if (grepl("^[0-9]", s)) s <- paste0("N", s)
    s
  }

  # Wrap a label in the correct Mermaid shape delimiters
  .mnode <- function(id, label, shape) {
    id  <- .mid(id)
    lbl <- gsub('"',  "#quot;", label)
    lbl <- gsub("\n", "<br/>",  lbl,  fixed = TRUE)
    switch(tolower(trimws(shape)),
      circle  = sprintf('%s(("%s"))', id, lbl),
      ellipse = sprintf('%s(["%s"])',  id, lbl),
      diamond = sprintf('%s{"%s"}',    id, lbl),
      rounded = sprintf('%s("%s")',    id, lbl),
      sprintf('%s["%s"]', id, lbl)   # rect / default
    )
  }

  eop <- if (directed) "-->" else "---"

  out <- c(
    "%% Generated by graphout::graph_to_outputs()",
    "%% Note: x/y coordinates are ignored — Mermaid uses automatic layout.",
    if (directed) "flowchart TD" else "flowchart TD",
    ""
  )

  # Node declarations (must appear before edges to fix shape)
  out <- c(out, "  %% Node declarations")
  for (i in seq_len(n))
    out <- c(out,
             paste0("  ", .mnode(np$id[i], as.character(np$label[i]),
                                 np$shape[i])))

  out <- c(out, "")

  # Edges
  out  <- c(out, "  %% Edges")
  done <- matrix(FALSE, n, n)
  for (i in seq_len(n)) {
    for (j in seq_len(n)) {
      v <- adj[i, j]
      if (v == 0 || (!directed && done[j, i])) next
      lbl_txt <- NULL
      if (!is.null(edge_labels) && !is.na(edge_labels[i, j]) &&
          nzchar(trimws(as.character(edge_labels[i, j]))))
        lbl_txt <- trimws(as.character(edge_labels[i, j]))
      else if (v != 1)
        lbl_txt <- format(v, trim = TRUE)
      lbl_part <- if (!is.null(lbl_txt)) paste0('|"', lbl_txt, '"|') else ""
      # Per-edge Mermaid operator based on linetype
      ep_lt_mmd <- NULL
      if (!is.null(edge_props)) {
        idx <- which(edge_props$weight == v)
        if (length(idx) > 0L && "linetype" %in% names(edge_props) && !is.na(edge_props$linetype[idx[1L]]))
          ep_lt_mmd <- edge_props$linetype[idx[1L]]
      }
      eop_this <- if (!is.null(ep_lt_mmd) && ep_lt_mmd != "solid") {
        if (directed) "-.->" else "-.-"
      } else eop
      out  <- c(out, sprintf("  %s %s%s %s",
                             .mid(np$id[i]), eop_this, lbl_part, .mid(np$id[j])))
      done[i, j] <- TRUE
    }
  }

  if (!is.null(adj_ov)) {
    n_ov  <- nrow(adj_ov)
    # Mermaid dashed edge operators: -.-> (directed) or -.- (undirected)
    ov_eop <- if (directed) {
      if (ovstyle == "dashed") "-.->" else "-->"
    } else {
      if (ovstyle == "dashed") "-.-" else "---"
    }
    out  <- c(out, "  %% Overlay edges")
    done_ov <- matrix(FALSE, n_ov, n_ov)
    for (i in seq_len(n_ov)) {
      for (j in seq_len(n_ov)) {
        v <- adj_ov[i, j]
        if (v == 0 || (!directed && done_ov[j, i])) next
        ov_lbl_txt <- NULL
        if (!is.null(overlay_edge_labels) && !is.na(overlay_edge_labels[i, j]) &&
            nzchar(trimws(as.character(overlay_edge_labels[i, j]))))
          ov_lbl_txt <- trimws(as.character(overlay_edge_labels[i, j]))
        else if (v != 1)
          ov_lbl_txt <- format(v, trim = TRUE)
        lbl_part <- if (!is.null(ov_lbl_txt)) paste0('|"', ov_lbl_txt, '"|') else ""
        # Per-overlay-edge Mermaid operator based on linetype
        ovep_lt_mmd <- NULL
        if (!is.null(overlay_edge_props)) {
          idx <- which(overlay_edge_props$weight == v)
          if (length(idx) > 0L && "linetype" %in% names(overlay_edge_props) && !is.na(overlay_edge_props$linetype[idx[1L]]))
            ovep_lt_mmd <- overlay_edge_props$linetype[idx[1L]]
        }
        ov_eop_this <- if (!is.null(ovep_lt_mmd)) {
          if (ovep_lt_mmd != "solid") {
            if (directed) "-.->" else "-.-"
          } else {
            if (directed) "-->" else "---"
          }
        } else ov_eop
        out  <- c(out, sprintf("  %s %s%s %s",
                               .mid(np$id[i]), ov_eop_this, lbl_part, .mid(np$id[j])))
        done_ov[i, j] <- TRUE
      }
    }
  }

  out <- c(out, "")

  # Per-node inline styles
  out <- c(out, "  %% Node styles")
  for (i in seq_len(n))
    out <- c(out, sprintf("  style %s fill:%s,stroke:%s,color:%s",
                          .mid(np$id[i]),
                          np$colour[i], np$stroke[i], np$fontcolour[i]))

  paste(out, collapse = "\n")
}
