# Internal functions for DOT and Mermaid output.
# None of these are exported; users interact only via graph_to_outputs().


# ── DOT builder ───────────────────────────────────────────────────────────────

#' @keywords internal
#' @noRd
.dot_build <- function(adj, np, directed) {
  n   <- nrow(adj)
  gkw <- if (directed) "digraph" else "graph"
  eop <- if (directed) "->"     else "--"

  # Wrap a string in double-quotes, escaping any internal double-quotes
  .dq <- function(s) paste0('"', gsub('"', '\\"', s, fixed = TRUE), '"')

  dot_shape <- function(s) {
    switch(tolower(trimws(s)),
      circle  = "circle",
      ellipse = "ellipse",
      diamond = "diamond",
      rounded = "box",    # style="filled,rounded" applied separately
      "box"               # default
    )
  }
  dot_style <- function(s) {
    if (tolower(trimws(s)) == "rounded") "filled,rounded" else "filled"
  }

  out <- c(
    "// Generated by graphout::graph_to_outputs()",
    "// Render with fixed positions : neato -n -Tsvg graph.dot -o graph.svg",
    "// Render with auto layout     : dot   -Tsvg graph.dot -o graph.svg",
    sprintf("%s G {", gkw),
    '  graph [fontname="Helvetica" splines=true overlap=false]',
    '  node  [fontname="Helvetica" fixedsize=false]',
    '  edge  [fontname="Helvetica"]',
    ""
  )

  for (i in seq_len(n)) {
    lbl  <- gsub('"',  '\\"',  as.character(np$label[i]), fixed = TRUE)
    lbl  <- gsub("\n", "\\n",  lbl, fixed = TRUE)
    # Graphviz uses inches; convert px assuming 96 dpi
    w_in <- round(np$width[i]  / 96, 3)
    h_in <- round(np$height[i] / 96, 3)
    # Graphviz y-axis points upward; SVG y-axis points downward → negate y
    pos_str <- paste0(np$x[i], ",", -np$y[i], "!")

    attrs <- paste(
      paste0("label=",     .dq(lbl)),
      paste0("shape=",     dot_shape(np$shape[i])),
      paste0("style=",     .dq(dot_style(np$shape[i]))),
      paste0("fillcolor=", .dq(np$colour[i])),
      paste0("fontcolor=", .dq(np$fontcolour[i])),
      paste0("color=",     .dq(np$stroke[i])),
      paste0("fontsize=",  np$fontsize[i]),
      paste0("width=",     w_in),
      paste0("height=",    h_in),
      paste0("pos=",       .dq(pos_str))
    )
    out <- c(out, paste0("  ", .dq(np$id[i]), " [", attrs, "]"))
  }

  out <- c(out, "")

  done <- matrix(FALSE, n, n)
  for (i in seq_len(n)) {
    for (j in seq_len(n)) {
      v <- adj[i, j]
      if (v == 0 || (!directed && done[j, i])) next
      elbl    <- if (v != 1) paste0(" [label=", .dq(format(v, trim = TRUE)), "]") else ""
      out     <- c(out, paste0("  ", .dq(np$id[i]), " ", eop, " ",
                               .dq(np$id[j]), elbl))
      done[i, j] <- TRUE
    }
  }

  out <- c(out, "}")
  paste(out, collapse = "\n")
}


# ── Mermaid builder ───────────────────────────────────────────────────────────

#' @keywords internal
#' @noRd
.mmd_build <- function(adj, np, directed) {
  n <- nrow(adj)

  # Sanitise to a valid Mermaid node identifier: [A-Za-z0-9_], no leading digit
  .mid <- function(s) {
    s <- gsub("[^A-Za-z0-9_]", "_", s)
    if (grepl("^[0-9]", s)) s <- paste0("N", s)
    s
  }

  # Wrap a label in the correct Mermaid shape delimiters
  .mnode <- function(id, label, shape) {
    id  <- .mid(id)
    lbl <- gsub('"',  "#quot;", label)
    lbl <- gsub("\n", "<br/>",  lbl,  fixed = TRUE)
    switch(tolower(trimws(shape)),
      circle  = sprintf('%s(("%s"))', id, lbl),
      ellipse = sprintf('%s(["%s"])',  id, lbl),
      diamond = sprintf('%s{"%s"}',    id, lbl),
      rounded = sprintf('%s("%s")',    id, lbl),
      sprintf('%s["%s"]', id, lbl)   # rect / default
    )
  }

  eop <- if (directed) "-->" else "---"

  out <- c(
    "%% Generated by graphout::graph_to_outputs()",
    "%% Note: x/y coordinates are ignored — Mermaid uses automatic layout.",
    if (directed) "flowchart TD" else "flowchart TD",
    ""
  )

  # Node declarations (must appear before edges to fix shape)
  out <- c(out, "  %% Node declarations")
  for (i in seq_len(n))
    out <- c(out,
             paste0("  ", .mnode(np$id[i], as.character(np$label[i]),
                                 np$shape[i])))

  out <- c(out, "")

  # Edges
  out  <- c(out, "  %% Edges")
  done <- matrix(FALSE, n, n)
  for (i in seq_len(n)) {
    for (j in seq_len(n)) {
      v <- adj[i, j]
      if (v == 0 || (!directed && done[j, i])) next
      lbl_part <- if (v != 1) paste0('|"', format(v, trim = TRUE), '"|') else ""
      out  <- c(out, sprintf("  %s %s%s %s",
                             .mid(np$id[i]), eop, lbl_part, .mid(np$id[j])))
      done[i, j] <- TRUE
    }
  }

  out <- c(out, "")

  # Per-node inline styles
  out <- c(out, "  %% Node styles")
  for (i in seq_len(n))
    out <- c(out, sprintf("  style %s fill:%s,stroke:%s,color:%s",
                          .mid(np$id[i]),
                          np$colour[i], np$stroke[i], np$fontcolour[i]))

  paste(out, collapse = "\n")
}
